### ISSUE TITLE
undefined method `gsub' for nil:NilClass when the user agent is nil

### ISSUE THREAD

**Issue by hoffi** [SidOfc/browserino#1]
When the User-Agent is `nil` a `undefined method `gsub' for nil:NilClass` Exception is thrown.

I have got this error in a Rails-Application when i testet using Capybara with the default RackTest-Driver. The User-Agent seems to be `nil` there by default.

**Comment by SidOfc** [comment]
Hi @hoffi!

Thank you for reporting the issue, indeed I make the assumption that the user agent is present. I will fix it right away.

**Comment by hoffi** [comment]
Hi, thanks for the quick fix. Yes it works now 👍
